# Default values for devops-bookstore-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: devopsupskillregistryzkeri.azurecr.io/devopsupskill/devops-bookstore-frontend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  containerPort: 8080
  livenessProbe: /books
  readinessProbe: /books
